# 서버 포트 설정
server:
  port: 8085

# 스프링 설정
spring:
  # 데이터베이스 연동 설정
  datasource:
    url: jdbc:mariadb://localhost:3308/boarddb?allowPublicKeyRetrieval=true
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.board1.vo