spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board_db
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver

  mybatis:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.example.board1.vo

server:
  port: 8080
